# fly.toml app configuration file generated for trilliontape-data on 2026-09-16T04:05:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trilliontape-data'
primary_region = 'iad'

[build]
  image = 'ghcr.io/tursodatabase/libsql-server:latest'

[env]
  SQLD_HTTP_LISTEN_ADDR = '0.0.0.0:8080'
  SQLD_NODE = 'primary'

[[mounts]]
  source = 'trilliontape_libsql'
  destination = '/var/lib/sqld'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
